### ISSUE TITLE
Game crash

### ISSUE THREAD

**Issue by heckair** [ErrorMikey/JustHammers#17]
Hello, i got a game crash when I try to select a hammer

```
---- Minecraft Crash Report ----
// Don't be sad, have a hug! <3

Time: 2023-12-25 21:50:02
Description: Unexpected error

java.lang.IllegalAccessError: class pro.mikey.justhammers.client.SelectionOutlineRender tried to access private method 'void net.minecraft.client.renderer.LevelRenderer.renderShape(com.mojang.blaze3d.vertex.PoseStack, com.mojang.blaze3d.vertex.VertexConsumer, net.minecraft.world.phys.shapes.VoxelShape, double, double, double, float, float, float, float)' (pro.mikey.justhammers.client.SelectionOutlineRender is in module justhammers@82.0.0 of loader 'TRANSFORMER' @7bcecef6; net.minecraft.client.renderer.LevelRenderer is in module minecraft@1.20.2 of loader 'TRANSFORMER' @7bcecef6)
	at pro.mikey.justhammers.client.SelectionOutlineRender.render(SelectionOutlineRender.java:87) ~[just-hammers-neoforge-82.0.0.jar%23182!/:?] {re:classloading}
	at pro.mikey.justhammers.neoforge.HammersClientEvents.onWorldRenderLast(HammersClientEvents.java:19) ~[just-hammers-neoforge-82.0.0.jar%23182!/:?] {re:classloading}
	at net.neoforged.bus.EventBus.post(EventBus.java:386) ~[bus-7.2.0.jar%23104!/:?] {}
	at net.neoforged.bus.EventBus.post(EventBus.java:351) ~[bus-7.2.0.jar%23104!/:?] {}
	at net.neoforged.neoforge.client.ClientHooks.dispatchRenderStage(ClientHooks.java:274) ~[neoforge-20.2.86-universal.jar%23189!/:?] {re:classloading}
	at net.neoforged.neoforge.client.ClientHooks.dispatchRenderStage(ClientHooks.java:281) ~[neoforge-20.2.86-universal.jar%23189!/:?] {re:classloading}
	at net.minecraft.client.renderer.LevelRenderer.renderSectionLayer(LevelRenderer.java:1399) ~[client-1.20.2-20231019.002635-srg.jar%23184!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.LevelRenderer.renderLevel(LevelRenderer.java:986) ~[client-1.20.2-20231019.002635-srg.jar%23184!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.GameRenderer.renderLevel(GameRenderer.java:1281) ~[client-1.20.2-20231019.002635-srg.jar%23184!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.GameRenderer.render(GameRenderer.java:1043) ~[client-1.20.2-20231019.002635-srg.jar%23184!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.runTick(Minecraft.java:1200) ~[client-1.20.2-20231019.002635-srg.jar%23184!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.run(Minecraft.java:776) ~[client-1.20.2-20231019.002635-srg.jar%23184!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:231) ~[neoforge-20.2.86.jar:?] {re:classloading,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.neoforged.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:126) ~[loader-1.0.16.jar:1.0] {}
	at net.neoforged.fml.loading.targets.CommonLaunchHandler.clientService(CommonLaunchHandler.java:114) ~[loader-1.0.16.jar:1.0] {}
	at net.neoforged.fml.loading.targets.CommonClientLaunchHandler.runService(CommonClientLaunchHandler.java:24) ~[loader-1.0.16.jar:1.0] {}
	at net.neoforged.fml.loading.targets.CommonLaunchHandler.lambda$launchService$4(CommonLaunchHandler.java:108) ~[loader-1.0.16.jar:1.0] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:108) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:78) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) ~[bootstraplauncher-1.1.2.jar:?] {}


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at pro.mikey.justhammers.client.SelectionOutlineRender.render(SelectionOutlineRender.java:87) ~[just-hammers-neoforge-82.0.0.jar%23182!/:?] {re:classloading}
	at pro.mikey.justhammers.neoforge.HammersClientEvents.onWorldRenderLast(HammersClientEvents.java:19) ~[just-hammers-neoforge-82.0.0.jar%23182!/:?] {re:classloading}
	at net.neoforged.bus.EventBus.post(EventBus.java:386) ~[bus-7.2.0.jar%23104!/:?] {}
	at net.neoforged.bus.EventBus.post(EventBus.java:351) ~[bus-7.2.0.jar%23104!/:?] {}
	at net.neoforged.neoforge.client.ClientHooks.dispatchRenderStage(ClientHooks.java:274) ~[neoforge-20.2.86-universal.jar%23189!/:?] {re:classloading}
	at net.neoforged.neoforge.client.ClientHooks.dispatchRenderStage(ClientHooks.java:281) ~[neoforge-20.2.86-universal.jar%23189!/:?] {re:classloading}
	at net.minecraft.client.renderer.LevelRenderer.renderSectionLayer(LevelRenderer.java:1399) ~[client-1.20.2-20231019.002635-srg.jar%23184!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.LevelRenderer.renderLevel(LevelRenderer.java:986) ~[client-1.20.2-20231019.002635-srg.jar%23184!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.GameRenderer.renderLevel(GameRenderer.java:1281) ~[client-1.20.2-20231019.002635-srg.jar%23184!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
-- Affected level --
Details:
	All players: 1 total; [LocalPlayer['Beeennnn'/774, l='ClientLevel', x=344.20, y=-5.00, z=352.60]]
	Chunk stats: 289, 17
	Level dimension: minecraft:overworld
	Level spawn location: World: (256,86,352), Section: (at 0,6,0 in 16,5,22; chunk contains blocks 256,-64,352 to 271,319,367), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 90280 game time, 73593 day time
	Server brand: forge
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.ClientLevel.fillReportDetails(ClientLevel.java:481) ~[client-1.20.2-20231019.002635-srg.jar%23184!/:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:architectury.mixins.json:MixinClientLevel,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.fillReport(Minecraft.java:2386) ~[client-1.20.2-20231019.002635-srg.jar%23184!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.run(Minecraft.java:798) ~[client-1.20.2-20231019.002635-srg.jar%23184!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:231) ~[neoforge-20.2.86.jar:?] {re:classloading,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.neoforged.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:126) ~[loader-1.0.16.jar:1.0] {}
	at net.neoforged.fml.loading.targets.CommonLaunchHandler.clientService(CommonLaunchHandler.java:114) ~[loader-1.0.16.jar:1.0] {}
	at net.neoforged.fml.loading.targets.CommonClientLaunchHandler.runService(CommonClientLaunchHandler.java:24) ~[loader-1.0.16.jar:1.0] {}
	at net.neoforged.fml.loading.targets.CommonLaunchHandler.lambda$launchService$4(CommonLaunchHandler.java:108) ~[loader-1.0.16.jar:1.0] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:108) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:78) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) ~[bootstraplauncher-1.1.2.jar:?] {}


-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: vanilla, mod_resources

-- System Details --
Details:
	Minecraft Version: 1.20.2
	Minecraft Version ID: 1.20.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.8, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 1032258704 bytes (984 MiB) / 1386217472 bytes (1322 MiB) up to 4294967296 bytes (4096 MiB)
	CPUs: 16
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 7 5800X 8-Core Processor             
	Identifier: AuthenticAMD Family 25 Model 33 Stepping 2
	Microarchitecture: Zen 3
	Frequency (GHz): 3.80
	Number of physical packages: 1
	Number of physical CPUs: 8
	Number of logical CPUs: 16
	Graphics card #0 name: AMD Radeon RX 6750 XT
	Graphics card #0 vendor: Advanced Micro Devices, Inc. (0x1002)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x73df
	Graphics card #0 versionInfo: DriverVersion=31.0.23013.1023
	Memory slot #0 capacity (MB): 16384.00
	Memory slot #0 clockSpeed (GHz): 2.67
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 16384.00
	Memory slot #1 clockSpeed (GHz): 2.67
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 37557.59
	Virtual memory used (MB): 20943.18
	Swap memory total (MB): 4864.00
	Swap memory used (MB): 52.96
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx4096m -Xms256m
	JVM uptime in seconds: 18.419
	Launched Version: neoforge-20.2.86
	Backend library: LWJGL version 3.3.2+13
	Backend API: AMD Radeon RX 6750 XT GL version 4.6.0 Core Profile Context 23.12.1.231124, ATI Technologies Inc.
	Window size: 854x480
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'neoforge'
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Resource Packs: vanilla, mod_resources
	Current Language: en_us
	Locale: en_US
	CPU: 16x AMD Ryzen 7 5800X 8-Core Processor 
	ModLauncher: 10.0.9+10.0.9+main.dcd20f30
	ModLauncher launch target: forgeclient
	ModLauncher naming: srg
	ModLauncher services: 
		mixin-0.8.5.jar mixin PLUGINSERVICE 
		loader-1.0.16.jar slf4jfixer PLUGINSERVICE 
		loader-1.0.16.jar object_holder_definalize PLUGINSERVICE 
		loader-1.0.16.jar runtime_enum_extender PLUGINSERVICE 
		loader-1.0.16.jar capability_token_subclass PLUGINSERVICE 
		at-modlauncher-10.0.1.jar accesstransformer PLUGINSERVICE 
		loader-1.0.16.jar runtimedistcleaner PLUGINSERVICE 
		modlauncher-10.0.9.jar mixin TRANSFORMATIONSERVICE 
		modlauncher-10.0.9.jar fml TRANSFORMATIONSERVICE 
	FML Language Providers: 
		lowcodefml@1.0
		minecraft@1.0
		javafml@1.0
	Mod List: 
		client-1.20.2-20231019.002635-srg.jar             |Minecraft                     |minecraft                     |1.20.2              |DONE      |Manifest: a1:d4:5e:04:4f:d3:d6:e0:7b:37:97:cf:77:b0:de:ad:4a:47:ce:8c:96:49:5f:0a:cf:8c:ae:b2:6d:4b:8a:3f
		RoughlyEnoughItems-13.0.685-neoforge.jar          |Roughly Enough Items (REI)    |roughlyenoughitems            |13.0.685            |DONE      |Manifest: NOSIGNATURE
		cloth-config-12.0.119-neoforge.jar                |Cloth Config v12 API          |cloth_config                  |12.0.119            |DONE      |Manifest: NOSIGNATURE
		architectury-10.0.17-neoforge.jar                 |Architectury                  |architectury                  |10.0.17             |DONE      |Manifest: NOSIGNATURE
		just-hammers-neoforge-82.0.0.jar                  |Just Hammers                  |justhammers                   |82.0.0              |DONE      |Manifest: NOSIGNATURE
		neoforge-20.2.86-universal.jar                    |NeoForge                      |neoforge                      |20.2.86             |DONE      |Manifest: NOSIGNATURE
	Crash Report UUID: 898070e0-8030-4455-aec4-268d681f1b94
	FML: 20.2
	NeoForge: net.neoforged:20.2.86
```

**Comment by MichaelHillcox** [comment]
Hmm, thanks, I'll take a look at this

**Comment by MichaelHillcox** [comment]
Should be fixed in the latest version :D https://modrinth.com/mod/just-hammers/version/ZucSI94r
